feat: using CountriesContext in the useFetchCountryByName hook
AlanPinhon/rest-countries-api-ts pull request #11
Opened 2024-01-12 19:55 UTC by AlanPinhon

Se aplicarán enlaces en la sección de fronteras (`borders`) en el componente `CountryPage` para llevar a la información del país seleccionado. 🔗 ↗ 🏳

Nota: se reemplazará la llamada a la API para utilizar el `context`. 🔄 ✅

2024-01-12 19:58 UTC, gonzalo-novak approved these changes

2024-01-14 02:55 UTC, AlanPinhon commented
Ya se muestran los países fronterizos (en caso de existir) y se enlazan a su información respectiva.
El título del `header` lo transformé a un enlace que lleva a la página de inicio.

Solo faltaría enlazar también al inicio en caso de no existir el país en el query param (ejemplo: /country/mechico ---> /home) 🐱‍👤

2024-01-14 03:34 UTC, gonzalo-novak submitted a review, later dismissed
¡Bien!

2024-01-14 19:31 UTC, AlanPinhon commented
Está hecha la redirección al `HomePage` en caso de no existir el país en el query param. ➡🏠

2024-01-15 18:30 UTC, gonzalo-novak requested changes

2024-01-15 18:30 UTC, gonzalo-novak commented on src/hooks/useFetchCountryByName.ts
> +      setCountryExist(true)
Lo que puedes hacer es setear el countryData sin importar si viene nulo o no

```tsx
setCountry(countryData)
```

Si country data no es [Truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy), entonces haces la redirección:

```tsx
const countryData = useFetchByCountryName(name) // <- También hay que cambiar el nombre de esta función puesto que ya no hace fetch de nada

 if(!countryData){
    return <Navigate to="/home"/>
  }
  
  const { prop1, prop2, prop3, ...rest } = countryData 
```

2024-01-15 23:55 UTC, AlanPinhon commented on src/hooks/useFetchCountryByName.ts
> +      setCountryExist(true)
Esa primera opción la hice, pero no me hace la redirección. En lugar de eso, me marca un error de que no se pueden leer propiedades de `undefined`. Entonces opté por agregar ese nuevo estado. 👨🏼‍🔧

![image](https://github.com/AlanPinhon/rest-countries-api-ts/assets/74801980/61fab5c8-5a5a-4dde-a8c1-170d4cc63ba4)

2024-01-16 01:09 UTC, gonzalo-novak approved these changes

2024-01-16 03:12 UTC, merged