style: theme color, loading text and error alert styles
AlanPinhon/rest-countries-api-ts pull request #17
Opened 2024-02-01 02:30 UTC by AlanPinhon

- Estilos en el texto de carga, mensaje de error y el modo claro y oscuro. 🖌
- Se persiste el tema en el local storage. 🏠

2024-02-01 17:15 UTC, gonzalo-novak requested changes

2024-02-01 17:15 UTC, gonzalo-novak commented on src/components/Header/Header.tsx
> +        <p className="theme-mode-text">Dark Mode</p>
¡Bien! Sólo veo que hace falta hacer switch de este HTML cuando el tema cambia. El mismo texto persiste aún cuando el tema es claro 👀

2024-02-01 19:32 UTC, AlanPinhon commented on src/components/Header/Header.tsx
> +        <p className="theme-mode-text">Dark Mode</p>
Cierto, aunque en el diseño no aparece ese switch, ya está actualizado en el código.  🔄

2024-02-02 04:03 UTC, gonzalo-novak requested changes

2024-02-02 04:03 UTC, gonzalo-novak commented on src/components/Header/Header.tsx
>          <img src={Moon} className="icon"/>
Sugiero que también se cambie el icono de la luna por el icono de un sol cuando se hace el swtich:

https://dribbble.com/shots/6594941-Theme-Toggle <- Sólo es una referencia, no se tiene que hacer tal cual como se ve en ese diseño

2024-02-02 04:38 UTC, AlanPinhon commented on src/components/Header/Header.tsx
>          <img src={Moon} className="icon"/>
Ya está el cambio de ícono cuando se cambia el modo claro u oscuro. ☀ 🔄 🌙

2024-02-02 17:38 UTC, gonzalo-novak approved these changes
¡Vientos! 👏🏻

2024-02-02 17:41 UTC, merged