feat: routes have been created
AlanPinhon/rest-countries-api-ts pull request #2
Opened 2023-12-07 23:14 UTC by AlanPinhon

Se crean rutas para las páginas de inicio y detalles de los países. 🔗

2023-12-07 23:28 UTC, gonzalo-novak requested changes

2023-12-07 23:28 UTC, gonzalo-novak commented on src/routes/CountriesAppRouter.tsx
> +        <Route path="detail" element={<DetailPage />} />
Si esta página es para mostrar el detalle de cada país, tal vez necesites añadirle un param a la ruta para que, posteriormente, lo puedas usar para traer data de algún servicio (en este caso, en el API debe haber algún endpoint que pueda traer la info de un país por su id).

https://reactrouter.com/en/main/start/concepts#defining-routes

```tsx
<Route path="detail/:countryId" element={<DetailPage />}
```

2023-12-07 23:34 UTC, AlanPinhon commented on src/routes/CountriesAppRouter.tsx
> +        <Route path="detail" element={<DetailPage />} />
Si, esa página es para mostrar el detalle de cada país, solo que lo dejé así de momento solo porque quería rectificar que las rutas estuviesen organizadas de manera correcta. De hecho el nombre del componente se lo cambiaré más adelante a `<CountryInfo/>` y ya ahí va toda la información. 🦅

2023-12-08 18:07 UTC, AlanPinhon commented
Ya está hecho el cambio de nombre del componente. 🤓

2023-12-09 00:56 UTC, gonzalo-novak approved these changes

2023-12-09 04:41 UTC, merged