feat: getCountries function and types created
AlanPinhon/rest-countries-api-ts pull request #3
Opened 2023-12-09 21:35 UTC by AlanPinhon

Creación de la función ascíncrona `getCountries` y tipado de su respuesta. 🔄

2023-12-09 22:12 UTC, gonzalo-novak approved these changes

2023-12-09 22:12 UTC, gonzalo-novak commented on src/types/CountriesTypes.ts
> +}
Sólo procura que los nombres se entiendan. Por ahora desconozco el por qué de estos nombres

2023-12-09 22:12 UTC, gonzalo-novak commented on src/types/CountriesTypes.ts
Los nombres de ciertos types se notan ambiguos. Sin embargo, creo que los types de la respuesta final (CountriesData) pueden dar una idea general de qué va. 🐰

2023-12-10 18:56 UTC, AlanPinhon commented on src/types/CountriesTypes.ts
> +}
Los nombres los generó una página que se llama "Paste JSON as Code". En sí no voy a ocupar todos porque hacerlos manualmente me iba a llevar más trabajo, pero los puedo cambiar para darle más sentido a que se refieren.

2023-12-10 19:00 UTC, AlanPinhon commented on src/types/CountriesTypes.ts
Justamente ese lo cambié para hacerle más sentido a la respuesta que se recibe, pero puedo cambiar los tipos para que no sean ambiguos. 🐱‍👤

2023-12-11 18:28 UTC, gonzalo-novak requested changes

2023-12-11 18:28 UTC, gonzalo-novak commented on src/types/CountriesTypes.ts
> +  AUD?: ArabEmiratesDirhamsExchangeRate;
No creo que el schema tenga algo que ver con los emiratos árabes xD

Me imagino que más bien es el schema del nombre de la divisa junto con su símbolo, por ejemplo:

```ts
{
  MXN: {
    name: "Mexican Peso",
    symbol: "$"
  }
}
```

En ese caso, el type podría ser el singular de "currencies" el cual es "currency" (bueno, currency puede ser usado como plural, pero en este caso ya tienes definido la forma plural como "currencies") 🐇

2023-12-11 18:28 UTC, gonzalo-novak commented on src/types/CountriesTypes.ts
> +export type ArabEmiratesDirhamsExchangeRate = {
Aquí es donde creo que el type debería llamarse "Currency"

2023-12-11 18:28 UTC, gonzalo-novak commented on src/types/CountriesTypes.ts
> +  SDG?: BosniaConvertibleMarksExchangeRate;
Aquí tal vez puedes usar un `Pick` del type `Currency` para tomar sólo el nombre:

`SDG?: Pick<Currency, "name">;`

Y por ende, podrías eliminar ese type si es el único lugar en donde es usado :D

2023-12-11 19:38 UTC, AlanPinhon commented on src/types/CountriesTypes.ts
> +  AUD?: ArabEmiratesDirhamsExchangeRate;
Fue lo que investigué más que nada por las siglas, pero tiene más sentido el dejar simplemente "currerncy" para ser más notable y lógico que es la moneda o denominación. Lo actualizaré.👻

2023-12-11 20:05 UTC, gonzalo-novak approved these changes

2023-12-11 20:39 UTC, merged