Feat/home-page-region
AlanPinhon/rest-countries-api-ts pull request #6
Opened 2023-12-22 01:05 UTC by AlanPinhon

Se filtran y muestran en pantalla los países por su región. 🔎

2023-12-22 19:06 UTC, gonzalo-novak requested changes

2023-12-22 19:06 UTC, gonzalo-novak commented on src/components/SearchSelect/SearchSelect.tsx
> +    setEndpointValue((region !== 'all')  ? `region/${region}`  : 'all')
Siento que esta lógica debería ir en la función `getCountries` donde recibas los parámetros de estos inputs y ahí ya centralizas todas las validaciones 🐇

2023-12-30 02:07 UTC, AlanPinhon commented on src/components/SearchSelect/SearchSelect.tsx
> +    setEndpointValue((region !== 'all')  ? `region/${region}`  : 'all')
Siento mucho la demora, pero este ajuste me costó un poco de trabajo para refactorizar los códigos y poder validar en `getCountries`. Funciona pero siento que se puede hacer algo más práctico y sencillo, pero quiero saber si la forma recién actualizada también es correcta. 👽

2023-12-30 03:15 UTC, gonzalo-novak requested changes
Siento que el approach actual puede no ser compatible cuando necesitemos buscar paises por nombre y región al mismo tiempo. Es decir, si quieres buscar un país por su nombre dentro de la región "Antartic", no se va a poder con la lógica actual 🤖

2023-12-30 03:15 UTC, gonzalo-novak commented on src/helpers/getCountries.ts
> +  if((endpoint === 'region' || endpoint === 'name') && value !== 'all') {
Tal vez lo que me hace dudar sobre esta lógica es que sólo buscaría ya sea por región o por nombre pero no por ambos, debido al mismo tema que tenemos con la API donde no podemos buscar ambas cosas al mismo tiempo (hasta donde he visto). Tal vez el approach que me comentaste de traer todos los países y luego filtrarlos con JS se me hace lo más cercano a poder buscar tanto por región como por el nombre al mismo tiempo 🐮 

Cualquier duda, avísame 💯

2023-12-30 03:15 UTC, gonzalo-novak commented on src/pages/HomePage/HomePage.tsx
> +      console.error(error)
Por ahora está bien este try-catch si necesitas mostrar un error en pantalla en caso de que haya un error. De lo contrario, no tendría mucho sentido tener el try-catch si hacemos sólo el console.error ya que estaríamos imitando el comportamiento por default 🐱

2023-12-30 18:58 UTC, AlanPinhon commented on src/helpers/getCountries.ts
> +  if((endpoint === 'region' || endpoint === 'name') && value !== 'all') {
Justamente en la documentación no hay una sección donde se busquen países por nombre dentro de una región. Se puede filtrar así:` https://restcountries.com/v3.1/all?fields=name,capital,currencies`. Dentro de los países solo se pueden llamar ciertos campos, pero no como lo buscamos filtrar nosotros. Entonces haré la corrección de solo traer todos los países y en JS hacer la filtración. 🦕

![image](https://github.com/AlanPinhon/rest-countries-api-ts/assets/74801980/2875064b-6144-40e4-be76-25623bb9acc5)

2023-12-30 19:00 UTC, AlanPinhon commented on src/pages/HomePage/HomePage.tsx
> +      console.error(error)
Ese error en un futuro tengo pensado mostrar un mensaje de error si el país ingresado en el input no existe. Algo así como en el proyecto de generador de consejos. Es una idea de momento, pero por ahora dejé así ese try-catch. 🐱‍💻

2024-01-02 23:22 UTC, AlanPinhon commented
He cambiado la forma de filtrar los países. Ahora se mandan llamar todos y mediante JS se filtran de momento por región. Si hay alguna observación o comentario estoy al tanto. 🐱‍💻

2024-01-03 03:08 UTC, gonzalo-novak approved these changes

2024-01-03 17:42 UTC, merged