chore: countries are filtered by name, region and both
AlanPinhon/rest-countries-api-ts pull request #7
Opened 2024-01-04 00:55 UTC by AlanPinhon

Se filtran los países por nombre, región (establecido en el anterior PR) y ambos. 🏳🏴‍☠️🎌

2024-01-04 02:01 UTC, gonzalo-novak requested changes

2024-01-04 02:01 UTC, gonzalo-novak commented on src/helpers/getCountriesByFilter.ts
> +    return countries.filter(country => country.region === regionValue).filter(country => country.name.common.includes(searchValue));
Adicionalmente, revisa que el filtrado no sea case-sensitive. Si busco el país `Mexico` de la siguiente manera, no me va a arrojar ningún resultado:

![Screenshot 2024-01-03 at 7 59 28 p m](https://github.com/AlanPinhon/rest-countries-api-ts/assets/51218118/a415a797-e3b3-49a7-b4ae-b653859bd87f)

2024-01-04 05:42 UTC, AlanPinhon commented
He hecho los siguientes ajustes:

La lógica que se encontraba en al componente `HomePage` donde se hacía la filtración la combiné con la función `getCountriesByFilter`, creando un custom hook llamado `useFilterCountries`, en el cual se maneja el estado a partir de una única llamada a la API y sobre el mismo estado se realizan las filtraciones requeridas. Se mantienen los argumentos de la región y el nombre y solo se insertan dichos valores en el componente `HomePage`. ⚙

Al igual que en el proyecto de los consejos, si bloqueo las solicitud URL en el navegador y posteriormente hago las filtraciones, las realiza sin ningún problema. ❌✅

Mucho texto, pero si hay algún comentario ahí ando pendiente. 🤓

2024-01-04 23:55 UTC, gonzalo-novak requested changes

2024-01-04 23:55 UTC, gonzalo-novak commented on src/hooks/useFilterCountries.ts
> +  }
Si añades esta lógica dentro de un `useEffect` y añades los argumentos que recibe el hook en la lista de dependencias, evitarás renders innecesarios puesto que sólo retornas la lista de países cuando esos 2 argumentos cambian:

```tsx
import { useEffect, useState, useMemo } from 'react';
import { CountriesData } from '../types/CountriesTypes';
import { getCountries } from '../helpers/getCountries';

export const useFilterCountries = (regionValue: string, searchValue: string) => {
  const [countries, setCountries] = useState<CountriesData[]>([]);
  const [filteredCountries, setFilteredCountries] = useState<CountriesData[]>([]);

  const getCountriesData = async () => {
    try {
      const countriesInfo: CountriesData[] = await getCountries();
      setCountries(countriesInfo);
    } catch (error) {
      console.error(error);
    }
  };

  useEffect(() => {
    getCountriesData();
  }, []);

  useEffect(() => {
    const region = ['Africa', 'Americas', 'Antarctic', 'Asia', 'Europe', 'Oceania'];
    let result = countries;

    if (region.includes(regionValue)) {
      result = result.filter(country => country.region === regionValue);
    }
    
    if (searchValue) {
      result = result.filter(country => country.name.common.includes(searchValue));
    }

    setFilteredCountries(result);
  }, [regionValue, searchValue, countries]);

  return filteredCountries;
};
```

2024-01-04 23:55 UTC, gonzalo-novak commented on src/hooks/useFilterCountries.ts
> +      console.error(error)
Recuerda, si no vas a mostrar algún error en pantalla, no tendría sentido meter un try-catch ya que actualmente se está replicando el comportamiento por default cuando sucede un error

2024-01-04 23:55 UTC, gonzalo-novak commented on src/components/SearchInput/SearchInput.tsx
> +    const countryCapitalizedFirstLetter = countryName.charAt(0).toUpperCase() + countryName.slice(1);
Creo que el filtrado lo puedes hacer en el hook convirtiendo los textos en minúscula:

```tsx
result = result.filter(country => country.name.common.toLowerCase().includes(searchValue.toLowerCase()));
```

2024-01-05 02:01 UTC, AlanPinhon commented
Se han hecho los cambios mencionados en el hook y para mantener el `trycatch` le añadí un mensaje de error y otro de carga mientras se realiza la llamada a la API.

2024-01-05 19:09 UTC, gonzalo-novak approved these changes

2024-01-05 19:45 UTC, merged