feat: link to CountryPage component
AlanPinhon/rest-countries-api-ts pull request #9
Opened 2024-01-06 18:06 UTC by AlanPinhon

Al dar click en el nombre del país, debe llevar a la página donde se muestre información detallada del mismo. 🗨🏳

2024-01-06 20:06 UTC, gonzalo-novak approved these changes

2024-01-06 20:07 UTC, gonzalo-novak commented
Solo se un poco específico en tus descripciones.  Como tal no se muestra ninguna info del pais cuando se hace la redireccion

2024-01-06 20:53 UTC, AlanPinhon commented
Lo que pasa es que aquí tengo pensado hacer ambas cosas. Solo iba a crear el PR y ya teniendo todo iba a agregarte en los Reviewers. 🤓

2024-01-07 05:53 UTC, AlanPinhon commented
Ahora si se muestra la información del país. Sé que tal vez se pueda refactorizar algo de código para que el componente no luzca muy saturado, pero estoy atento a cualquier observación. 🐱‍👤

2024-01-08 18:35 UTC, gonzalo-novak requested changes

2024-01-08 18:35 UTC, gonzalo-novak commented on src/helpers/getCurrenciesValues.ts
> +    return currencies ? currencies[key as keyof Currencies] : { name: "", symbol: "" };
Siento que más bien la validación pudiera ser en plan:

```suggestion
    return currencies[key as keyof Currencies] || { name: "", symbol: "" };
```

Ya que los currencies va a venir como un objeto con una propiedad o vacío en todo caso según los types. 🐱

2024-01-08 18:35 UTC, gonzalo-novak commented on src/helpers/getCurrenciesValues.ts
> +  const currenciesKeys = Object.keys(currencies || {});
Lo mismo pasa aquí: Los types indican que el objeto puede que venga vacío o con una propiedad, por ende sólo le puedes referenciar los currencies:

```suggestion
  const currenciesKeys = Object.keys(currencies);
```

Pero si TS te marcó un error y esa fue la forma de mitigarlo, estoy OK 👌🏻

2024-01-08 18:35 UTC, gonzalo-novak commented on src/helpers/getLanguagesValue.ts
> +export const getLanguagesValue = (languages:{ [key: string]: string }) => {
Siempre es mejor hacer referencia a los types que ya existen para no repetir el mismo código:

```suggestion
export const getLanguagesValue = (languages: CountriesData["languages"]) => {
```

2024-01-08 18:35 UTC, gonzalo-novak commented on src/helpers/getLanguagesValue.ts
> +    return languages && languages[key as keyof { [key: string]: string }]
```suggestion
    return languages && languages[key as keyof CountriesData["languages"]]
```

2024-01-08 18:35 UTC, gonzalo-novak commented on src/helpers/getLanguagesValue.ts
> +  const languagesKeys = Object.keys(languages || {});
Como la propiedad `languages` puede no existir, lo ideal sería retornar un null o algo que indique que dicha propiedad no debe ser renderizada

2024-01-08 18:35 UTC, gonzalo-novak commented on src/helpers/getNativeNamesValues.ts
> +    return name?.nativeName ? name.nativeName[key] : { official: "", common: "" }
Más que retornar un objeto con propiedades vacías, retorna las propiedades con su respectivo valor, aunque no estoy seguro si utilizas realmente ese objeto cuando no existe un `nativeName`:

```suggestion
    return name?.nativeName ? name.nativeName[key] : { official: name.official, common: name.common }
```

2024-01-08 18:35 UTC, gonzalo-novak commented on src/hooks/useFetchCountryByName.ts
> +    const countryData = countriesInfo.find(country => country.name.common.toLowerCase() === name.toLowerCase().split('-').join(' '));
No creo que traer todos los países para sólo escoger uno sea lo más ideal. Hay un endpoint que puede ser usado para buscar únicamente por el nombre del país:

https://restcountries.com/#endpoints-name

Trata de poner como prioridad el hecho de poder filtrar desde el back-end mediante los endpoints que éste expone, si no hay manera alguna de hacerlo, lo ideal es que lo hables con el back-end developer, pero como este no es el caso, tocaría filtrar vía JS, pero este no es el caso 🥬

2024-01-08 18:35 UTC, gonzalo-novak commented on src/pages/CountryPage/CountryPage.tsx
El hook debería retornar el objeto con las propiedades listas para ser usadas en tu JSX. El approach que utilizase para separar lógica en mini funciones para ir obteniendo los datos necesarios me parece bien, pero esas funciones deberían estar dentro del hook 👌🏻

2024-01-09 19:30 UTC, AlanPinhon commented
Ya están realizadas algunas correcciones que me mencionaste, además de otras refactorizaciones en el tipado `Currencies`. Solo faltaría agregar la funcionalidad de regresar a la página principal al presionar el enlace de `back`, además de posiblemente mostrar una página de error en caso de que la ruta al país no exista o de regresarlo a la página principal. 🔄

2024-01-09 20:28 UTC, gonzalo-novak requested changes
Veo unas cosas que se pueden pulir

2024-01-09 20:28 UTC, gonzalo-novak commented on src/helpers/getCountries.ts
> +  let url = `https://restcountries.com/v3.1/`;
Puedes mandarle el endpoint directo:

```suggestion
  let url = `https://restcountries.com/v3.1/${endpoint || "all"}`;
```

Ya cuando se utilize puedes hacer algo como:

```tsx
await getCountries(`/name/${countryName}`)
```

2024-01-09 20:28 UTC, gonzalo-novak commented on src/types/CountriesTypes.ts
> -export type Currencies = {
¿Por qué se eliminó esto? 🤔

2024-01-09 20:28 UTC, gonzalo-novak commented on src/pages/CountryPage/CountryPage.tsx
> +              {(languagesName && currencyName.length > 0) ? languagesName.map(language => language).sort().join(', ') : "N/A"} </p>
Creo que el `.map` está de más, salvo que esté equivocado:

```suggestion
              {(languagesName && currencyName.length > 0) ? languagesName.sort().join(', ') : "N/A"} </p>
```

Adicionalmente, si se piensa convertir ese array en un string, lo ideal es que este dato se manipule dentro del hook para que te lo retorne ya con el formato deseado (a no ser que el `languagesName` se utilice en otras partes)

2024-01-09 20:28 UTC, gonzalo-novak commented on src/helpers/getNativeNamesValues.ts
Estos archivos estaban bien, lo que se tendría que hacer es importar dichas funciones en el hook para que puedan ser usadas

2024-01-09 20:28 UTC, gonzalo-novak commented on src/pages/CountryPage/CountryPage.tsx
> +            <strong>Capital: <p className='country-value'>{(capital) ? capital : "N/A"}</p> </strong>
```suggestion
            <strong>Capital: <p className='country-value'>{capital || "N/A"}</p> </strong>
```

2024-01-09 22:40 UTC, AlanPinhon commented on src/types/CountriesTypes.ts
> -export type Currencies = {
Eso lo eliminé porque en cuanto al tipado mostraba cada una de las monedas del mundo y como es una propiedad dinámica, se realiza la misma funcionalidad que en las funciones (valga la redundancia) que cuando se obtiene la clave de los idiomas o de los nombres nativos de cada país. Entonces solo dejé la propiedad general `currencies?:  { [key: string]: Currency } ` y ya accede directamente al tipo `export type Currency = { name: string; symbol: string; }` ☝🏼🤓

2024-01-10 19:42 UTC, merged